export enum USDAFoodGroups {
  americanNativeFoods = 'American Indian/Alaska Native Foods',
  babyFoods = 'Baby Foods',
  bakedProducts = 'Baked Products',
  beef = 'Beef Products',
  beverages = 'Beverages',
  cereals = 'Breakfast Cereals',
  grains = 'Cereal Grains and Pasta',
  dairy = 'Dairy and Egg Products',
  fastFoods = 'Fast Foods',
  fatsOils = 'Fats and Oils',
  seaFood = 'Finfish and Shellfish Products',
  fruits = 'Fruits and Fruit Juices',
  lambVealGame = 'Lamb, Veal, and Game Products',
  legumes = 'Legumes and Legume Products',
  meals = 'Meals, Entrees, and Side Dishes',
  nutsSeeds = 'Nut and Seed Products',
  pork = 'Pork Products',
  poultry = 'Poultry Products',
  restaurantFoods = 'Restaurant Foods',
  sausages = 'Sausages and Luncheon Meats',
  snacks = 'Snacks',
  soupsSauces = 'Soups, Sauces, and Gravies',
  spicesHerbs = 'Spices and Herbs',
  sweets = 'Sweets',
  vegetables = 'Vegetables and Vegetable Products'
}

export enum USDAFoodGroupIds {
  'American Indian/Alaska Native Foods' = '2300',
  'Baby Foods' = '0300',
  'Baked Products' = '1800',
  'Beef Products' = '1300',
  'Beverages' = '1400',
  'Breakfast Cereals' = '0800',
  'Cereal Grains and Pasta' = '2000',
  'Dairy and Egg Products' = '0100',
  'Fast Foods' = '2100',
  'Fats and Oils' = '0400',
  'Finfish and Shellfish Products' = '1500',
  'Fruits and Fruit Juices' = '0900',
  'Lamb, Veal, and Game Products' = '1700',
  'Legumes and Legume Products' = '1600',
  'Meals, Entrees, and Side Dishes' = '2200',
  'Nut and Seed Products' = '1200',
  'Pork Products' = '1000',
  'Poultry Products' = '0500',
  'Restaurant Foods' = '2500',
  'Sausages and Luncheon Meats' = '0700',
  'Snacks' = '2400',
  'Soups, Sauces, and Gravies' = '0600',
  'Spices and Herbs' = '0200',
  'Sweets' = '1900',
  'Vegetables and Vegetable Products' = '1100'
}

